# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/wayde191/IHakulaSpecs.git'

platform :ios, '7.1'

# IHakulaInfrastructure common dependencies
def commonPods
    pod 'Reachability'
end

target 'IHakulaInfrastructure' do
    commonPods
end

target 'IHakulaInfrastructureTests' do
    commonPods
end

